"""
Core Data Schemas.

Defines the strictly typed data structures for inter-service communication
and agent payload handling.
"""

from pydantic import BaseModel, Field
from typing import Any, Dict, Optional


class AgentRequest(BaseModel):
    """Standardized input payload for all agents."""
    task_id: str = Field(..., description="Unique identifier for the task tracking.")
    prompt: str = Field(..., description="The main instruction or context for the agent.")
    metadata: Dict[str, Any] = Field(
        default_factory=dict, 
        description="Optional dynamic data (e.g., user preferences, system constraints)."
    )


class AgentResponse(BaseModel):
    """Standardized output payload from all agents."""
    task_id: str = Field(..., description="Must match the incoming task_id.")
    status: str = Field(..., pattern="^(success|failed|processing)$")
    result: Dict[str, Any] = Field(
        default_factory=dict, 
        description="The structured output generated by the AI."
    )
    error_message: Optional[str] = Field(
        default=None, 
        description="Populated only if the agent encounters an exception."
    )